# Generated by Django 4.0 on 2022-01-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKUEduSRLApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveoutput',
            name='save_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saveoutput',
            name='sid',
            field=models.CharField(max_length=64),
        ),
    ]
