# Generated by Django 4.0 on 2022-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HKUEduSRLApp', '0004_saveoutput_creat_time_saveoutput_learn_tast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='srlid',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
