# Generated by Django 4.0 on 2022-02-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HKUEduSRLApp', '0005_user_srlid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveoutput',
            name='learn_tast',
        ),
    ]
